[build]
  command = "npm ci && npm run build"
  publish = "dist/maniUnite/browser"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"

# Plugin oficial para Angular en Netlify
[[plugins]]
  package = "@netlify/angular-runtime"

# SPA: redirige todas las rutas a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200